In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("final.csv")
df.head()

,CASEID,RACE,AGE,FRSTUSE1,PREG,NOPRIOR,DSMCRIT,PSYPROB,SERVICES,REASON,SUB1,FREQ1,ROUTE1,FREQ_ATND_SELF_HELP,HIGH_RISK
0,1176586,5,8,1,0,1,5,0,7,4,2,1,1,1,1
1,1143727,5,8,1,0,1,15,1,4,4,2,3,1,1,0
2,9608,5,6,1,0,1,4,0,7,1,2,3,1,5,0
3,1121071,4,3,1,0,0,7,1,4,4,2,2,1,5,0
4,1463086,5,6,1,0,1,4,1,6,1,2,1,1,5,0

In [ ]:
# prepare the data
# target
y = df['HIGH_RISK']
# features
X = df[['RACE', 'AGE','REASON','FREQ1', 'ROUTE1']]

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
#training and testset split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [ ]:
#scale data to get ready for logistic
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
#apply logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)
y_prob_log = log_model.predict_proba(X_test_scaled)[:, 1]

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Precision:", precision_score(y_test, y_pred_log))
print("Recall:", recall_score(y_test, y_pred_log))
print("F1:", f1_score(y_test, y_pred_log))
print("AUC:", roc_auc_score(y_test, y_prob_log))

Logistic Regression
Accuracy: 0.7509945934917882
Precision: 0.7742923479721385
Recall: 0.6724152724152724
F1: 0.7197667210065897
AUC: 0.7989694443380497

In [ ]:
#apply random forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("\nRandom Forest")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1:", f1_score(y_test, y_pred_rf))
print("AUC:", roc_auc_score(y_test, y_prob_rf))

Random Forest
Accuracy: 0.7962664490462104
Precision: 0.8362269102654689
Recall: 0.7108108108108108
F1: 0.7684352100918282
AUC: 0.8715722778103637

In [ ]:
df2 = pd.read_csv("final_los.csv")
df2.head()

,CASEID,RACE,AGE,FRSTUSE1,PREG,NOPRIOR,DSMCRIT,PSYPROB,SERVICES,LOS_PERIOD,REASON,SUB1,FREQ1,ROUTE1,FREQ_ATND_SELF_HELP,METHUSE,BENZFLG,TRNQFLG,IDU
0,841622,5,8,1,0,1,5,0,7,0,4,2,1,1,1,1,0,0,0
1,1072442,5,8,1,0,1,5,0,7,0,4,2,1,1,1,1,0,0,0
2,793277,4,4,1,0,0,19,1,7,2,2,2,1,1,1,0,1,0,0
3,1623624,8,6,1,0,1,8,1,1,0,1,2,3,1,1,0,0,0,1
4,384375,7,3,1,0,0,19,1,7,2,7,2,3,1,1,1,0,0,0

In [ ]:
# prepare the data
# target
y2 = df2['LOS_PERIOD']
# features
X2 = df2[['SERVICES', 'REASON']]

In [ ]:
X2 = pd.get_dummies(X2, drop_first=True)

In [ ]:
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.3, random_state=42, stratify=y2
)

In [ ]:
X2_train_scaled = scaler.fit_transform(X2_train)
X2_test_scaled = scaler.transform(X2_test)

In [ ]:
log_model2 = LogisticRegression(max_iter=1000)

log_model2.fit(X2_train_scaled, y2_train)

y2_pred_log = log_model2.predict(X2_test_scaled)
y2_prob_log = log_model2.predict_proba(X2_test_scaled)

accuracy = accuracy_score(y2_test, y2_pred_log)
precision = precision_score(y2_test, y2_pred_log, average=None)
recall = recall_score(y2_test, y2_pred_log, average=None)
f1 = f1_score(y2_test, y2_pred_log, average=None)
auc = roc_auc_score(y2_test, y2_prob_log, multi_class='ovr', average=None)

classes = log_model2.classes_

metrics_df = pd.DataFrame({
    'Class'    : classes,
    'Precision': precision,
    'Recall'   : recall,
    'F1 Score' : f1,
    'AUC'  : auc
})

print(metrics_df.to_string(index=False))
print(f"Overall Accuracy: {accuracy_score(y2_test, y2_pred_log):.4f}\n")

 Class  Precision   Recall  F1 Score      AUC
     0   0.610350 0.906984  0.729672 0.705262
     1   0.000000 0.000000  0.000000 0.581691
     2   0.000000 0.000000  0.000000 0.652218
     3   0.300109 0.280132  0.289777 0.706475
Overall Accuracy: 0.5639

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
rf_model2 = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model2.fit(X2_train, y2_train)

y2_pred_rf = rf_model2.predict(X2_test)
y2_prob_rf = rf_model2.predict_proba(X2_test)

y2_prob_rf_alt = rf_model2.predict_proba(X2_test)

accuracy = accuracy_score(y2_test, y2_pred_rf)
precision = precision_score(y2_test, y2_pred_rf, average=None)
recall = recall_score(y2_test, y2_pred_rf, average=None)
f1 = f1_score(y2_test, y2_pred_rf, average=None)
auc = roc_auc_score(y2_test, y2_prob_rf, multi_class='ovr', average=None)

classes = rf_model2.classes_

metrics_df = pd.DataFrame({
    'Class'    : classes,
    'Precision': precision,
    'Recall'   : recall,
    'F1 Score' : f1,
    'AUC'  : auc
})

print(metrics_df.to_string(index=False))
print(f"Overall Accuracy: {accuracy_score(y2_test, y2_pred_rf):.4f}\n")

 Class  Precision   Recall  F1 Score      AUC
     0   0.778069 0.824949  0.800824 0.817704
     1   0.000000 0.000000  0.000000 0.674506
     2   0.404489 0.102627  0.163716 0.735940
     3   0.322350 0.701031  0.441629 0.763194
Overall Accuracy: 0.6025